#!/bin/bash

files=(
  .config/awesome/rc.lua
  .config/awesome/wibar.lua
  .local/bin/statusbar
  .local/bin/notetaker
  .bashrc
  .bash_profile
)

for file in "${files[@]}"; do
  [ ! -h "$HOME"/"$file" ] && ln -v -s -f "$PWD"/"$file" "$HOME"/"$file"
done

