#!/bin/sh

# The exernal key-handler for sxiv, Simple X Image Viewer
# First you have to press Ctrl-x to send the next key to the key-handler
#
# The current bindings:
# d - to remove selected images
# p - to print selected images' names
# r - to rotate selected images
# w - to set as a wallpaper with xwallpaper
# y - to yank selected images

_rotate() {
  degree="90"
  tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
    case "$(file -b -i "$file")" in
      image/jpeg*)
        jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
      *)
        mogrify  -rotate "$degree" "$file" ;;
    esac
  done
}

_delete() {
  while read file; do
    rm "$file"
  done
}

_print() {
  while read file; do
    echo "$file"
  done
}

_yank() {
  while read file; do
    xclip -selection clipboard -target image/png "$file"
  done
}

_set_wallpaper() {
  monitor=$(xrandr | grep " connected" | awk '{ print$1 }')
  while read file; do
    xargs xwallpaper --output $monitor --stretch "$file"
  done
}

case "$1" in
  "d") _delete        ;;
  "p") _print         ;;
  "r") _rotate        ;;
  "w") _set_wallpaper ;;
  "y") _yank          ;;
esac
