#!/bin/sh

# Compatibility for GNU and *BSD/Darwin
ls --color=auto &> /dev/null && alias ls="ls --color=auto" || alias ls="ls -G"
alias ll="ls -l"
alias la="ls -la"

alias rm="rm -Ir"
alias cp="cp -r"

alias grep="grep --color=auto"

alias vi="nvim"
alias ni="ninja"
alias me="meson"

alias pi="sudo pacman -S"
alias piu="sudo pacman -Syu"

if command -v loginctl &> /dev/null; then
    alias logout="loginctl terminate-session $(loginctl session-status | awk 'NR==1{print $1}')"
fi
