#!/bin/sh

# Compatibility for GNU and *BSD/Darwin
ls --color=auto &> /dev/null && alias ls="ls --color=auto" || alias ls="ls -G"
alias ll="ls -l"
alias la="ls -la"

rm() {
  print -c $@
}

#alias rm="rm -ir"
alias cp="cp -r"

alias grep="grep --color=auto"

alias vi="nvim"
alias ni="ninja"
alias me="meson"

alias pi="sudo pacman -S"
alias piu="sudo pacman -Syu"

#alias logout="loginctl terminate-session $(loginctl session-status | awk 'NR==1{print $1}')"

