#!/bin/sh

# Returns git or mercurial branch
git_branch() {
  branch=$(git branch 2>/dev/null | grep '^*' | colrm 1 2)
  [ -z "${branch}" ] && branch=$(hg branch 2>/dev/null)
  [ ! -z "${branch}" ] && echo " ${branch}"
}

# Returns the current time
get_time() {
  time=$(date +'%R')
  echo $time
}

# Sources the given file if one exists
source_if_exists() {
  [ -f ${1} ] && source ${1}
}

# Launch the given app if one exists
function launch_if_exists() {
    if command -v $1 &> /dev/null; then
        $1 &
    fi
}

# Returns true/false compatible with test, checks if apps for work must be run
function am_i_resting_now() {
    # For 2023
    holidays=(
        "January 01"
        "January 06"
        "April 09"
        "April 10"
        "May 01"
        "May 03"
        "May 28"
        "June 08"
        "August 15"
        "November 01"
        "November 11"
        "December 25"
        "December 26"
    )
    day="$(date +'%B %d')"
    for holiday in "${holidays[@]}"; do
        [[ "${day}" == "${holiday}" ]] && return
    done

    weekends=(
        "Saturday"
        "Sunday"
    )
    today="$(date +'%A')"
    for weekend in "${weekends[@]}"; do
        [[ "${today}" == "${weekend}" ]] && return
    done

    hours="$(date +'%H')"
    [[ ${hours} > "17" || ${hours} < "08" ]]
}

